language: cpp

env:
  global:
   - secure: "eDfO7u4h8JA8L6LOYalAFLgthOMci7t9aclMzKEVL34XZt+NKwrUeAtO58aYyxijc0FR/8vnJIe6Ukl6AHTXRQmUyWS0qtZCK8/e+/pYPI3ERWq/EgneQlVk4MolDI7AvraOZZEZUZ4wIFrdMxEaCIokslyYJrjNVCb76Qh2xdTbLLhWh5x2U4zI7BAXf9BX4jGJ/UO/srp15Y8Ivo5NeAn1YSLMBab+1GKY27jPlHquwaT7YrSqgBGfMVXF/H3lIYvrmwFpj2rX53otjfMGFNQGxUXcfkJdrkUHVZg0kiOcE+j9XSLZOoA1USHwO15fAlz+SkGCevgtmO1X5WxVhRj4pmJgEJLMUcemeLotK7Me4fjhU2Lu6QZqvBmACQb8lzqYKOx212L0m+6vVzzBAlfNLvEmq4XpxN4eg9hkKt48mQuwOYXVX6EtKf861PpYFd7lFGrsxnrfBhC4B1qsgpODro5P71k2FdKQWJNSrxgj6h9Wqw/j71gCDEuKX0FMdm0zUkob9O+fVatvBj2MfmMktuaXrqoVYGgwzHLyT0tIXxtZrfYtVF7elFYdHHv+2JToaA83XGPyvYeDGXtMKQ2vGs2V4nKxQBdZCna0DYIWdrTeEsVDWJ5tJYWMQAn752zytk3yIrk9JqWXFmni+vmjCdh7x1mzewTlBo2mTLk="

matrix:
  include:
  - os: osx
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: GIgIckH67VaSb8RhtbaBwZds7T/bH+Xbf9tU3vvY9dzLfZ8qh2RfHgQssPd8yNGdBnQuYj4nXp9Bzkw8Sx8BGx+SDrwLyf1BkIquk3jggkaa19gLmPAYq7ZFAW+D9oA9Oqwf6z5YI6z/jYOvrMwUjX94+AUhxGbO0/4ssCSsU6Yc76vzsWcsknbiPZmQxMghsXMZe69xi01Qcp5P1hBd71AnPv0ZJgh/jD8qHLU5uV8JLL+M+O1Lv4aRFOjJfVmokUaYjs+QrXOhwkAHPtKXarumkNTeQizzSL6vtRnF5Zuj1y8j97pePtryTN6PH1oZorxWsEJEANLqp9Gp6iqv8sNmrygfYY6unpTQZRGaiYd4qz2dEExZMNymdCofZ/Zk+zXfFlk1Yh6uOELRUB2v0vqDG/aa7nZhIBnz0ODrcvh64He+/+h6F/z5gLUmxkdqkjecH3zn/8AyiqMC1uYqIru6HbuBZyoMGjT9RvLJWt5CcP/jhdgoonxWEao8o21WHBI8u0o3608tsYguIWxMVfTmIl4xCUTp2FRcvqmmlvwUSkDFhz6YeXWdyVRb0cJQiKMD11wLiWrpLy3GDdpm/LBKhAtVJxVmVdMx+B+I0scWaoxsyoff6r4R20tPHGHxZkOMsdfRPW+8mvIXR3XaAKMODg+9pJvM/Wy/q5JYpNk=
      on:
        tags: true

  - os: osx
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild analyze -quiet -scheme AirportBrcmFixup -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme AirportBrcmFixup -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]

  - os: osx
    compiler: clang

    script:
      - echo "This script runs coverity..."

    addons:
      coverity_scan:
        project:
          name: "acidanthera/AirportBrcmFixup"
          description: "AirportBrcmFixup"
        notification_email: $NOTIFICATION_EMAIL
        build_command_prepend: "src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval \"$src\" || exit 1 ; src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/covstrap.sh) && eval \"$src\" || exit 1"
        build_command: "xcodebuild -configuration Release"
        branch_pattern: master
